apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oci-bv-claim-2
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: oci-bv
  resources:
    requests:
      storage: 50Gi
  volumeMode: Block
