apiVersion: v1
kind: Pod
metadata:
  name: rajat-test-1
spec:
  containers:
  - name: rajat-test-1
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: ps-test-1
      mountPath: /data
  volumes:
  - name: ps-test-1
    persistentVolumeClaim:
      claimName: oci-bv-claim-1
